[2020-02-14 16:09:16] [error] [/home/liboxian/ai_server/ai_g7/ai_g7/source/hmai/hmai_gate_nlp.py - 431 ] {'result': [{'code': '-1', 'mr': [], 'model': 'keyword#fnlp#cherry', 'error': 'ainame', 'error_mes': 'keyword#cherry#nlp bad ais parameter  at 2020-02-14-16:09:16 '}], 'pro_ver': '2.1'}
